modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="horrorofacespeke"
version="1.4.2"
displayName="The Horror Of Fake Acespeke"
credits="Created using mod maker MCreator - https://mcreator.net/about"
logoFile="logo.png"
authors="___Pumpkinn"
description="(test"

[[dependencies.horrorofacespeke]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"



[[dependencies.horrorofacespeke]]
modId="geckolib"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
